name: RewardPools
main: Aisu.RewardPools.RewardManager
version: 0.0.1
author: Aisuboirad
commands:
   RP:
      description: Gives you this help menu
      usage: /&lt;command&gt;
   RP Reload:
      description: Reloads the chance list
      permission: RewardPools_Manager.Reload
      usage: /&lt;command&gt;
   RP Give:
      description: gives a reward from the give rewardpool
      permission: RewardPools_Manager.Reward
      usage: /&lt;command&gt; <player> <rewardpool>